version: '3.3'
services:
    java-maven-app:
      image: rufat51/my-repo:2.0
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
